import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text} from 'react-native';
import DeviceInfo from 'react-native-device-info';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/types';
import {Button,Card,Field,Screen,styles} from '../components/ui';
import {AppHeader,BottomNavigation,type MainDestination} from '../components/AppChrome';
import {ModelService} from '../ai/ModelService';
import {DEFAULT_EMBEDDING_MODEL_ID,DEFAULT_LLM_MODEL_ID,LLM_MODEL_OPTIONS,getModelById} from '../ai/modelRegistry';
import {ContentRepository,DocumentRepository,SettingsRepository} from '../database/repositories';
import {useAppStore} from '../stores/useAppStore';
import {removePrivateFile} from '../documents/importer';
import {userMessage} from '../types/errors';
import {OllamaService} from '../ai/OllamaService';
import {defaultOllamaEmbeddingModel,defaultOllamaEndpoint,defaultOllamaGenerationModel,getAIProvider,getOllamaConfig,saveOllamaConfig,type AIProvider} from '../ai/providerConfig';

type Props=NativeStackScreenProps<RootStackParamList,'Settings'>;
export const SettingsScreen=({navigation}:Props)=>{const models=useAppStore(s=>s.models);const loadModels=useAppStore(s=>s.loadModels);const loadDocuments=useAppStore(s=>s.loadDocuments);const [chunk,setChunk]=useState('700');const [summaryLength,setSummaryLength]=useState('medium');const [status,setStatus]=useState('');const [progress,setProgress]=useState(0);const [busy,setBusy]=useState(false);const [version,setVersion]=useState('');
  const [provider,setProvider]=useState<AIProvider>('on_device');const [endpoint,setEndpoint]=useState(defaultOllamaEndpoint);const [generationModel,setGenerationModel]=useState(defaultOllamaGenerationModel);const [embeddingModel,setEmbeddingModel]=useState(defaultOllamaEmbeddingModel);
  const [modelBusyId,setModelBusyId]=useState<string|null>(null);const [activeIds,setActiveIds]=useState({llm:DEFAULT_LLM_MODEL_ID,embedding:DEFAULT_EMBEDDING_MODEL_ID});
  const refreshModels=async()=>{await loadModels();setActiveIds(await ModelService.getActiveModelIds());};
  useEffect(()=>{void(async()=>{const [savedChunk,savedProvider,ollama,ids]=await Promise.all([SettingsRepository.get('chunk_size'),getAIProvider(),getOllamaConfig(),ModelService.getActiveModelIds()]);if(savedChunk)setChunk(savedChunk);setProvider(savedProvider);setEndpoint(ollama.endpoint);setGenerationModel(ollama.generationModel);setEmbeddingModel(ollama.embeddingModel);setActiveIds(ids);})();setVersion(DeviceInfo.getVersion());},[]);
  const useLocalModel=async(modelId:string)=>{setModelBusyId(modelId);setProgress(0);try{const previousProvider=await getAIProvider();const installed=models.find(model=>model.id===modelId)?.status==='downloaded';const embeddingInstalled=models.find(model=>model.id===DEFAULT_EMBEDDING_MODEL_ID)?.status==='downloaded';if(!installed||!embeddingInstalled)await ModelService.downloadBundle(modelId,(value,label)=>{setProgress(value);setStatus(`${label} · ${Math.round(value*100)}%`);});else await ModelService.activate(modelId);if(previousProvider==='ollama')await DocumentRepository.clearEmbeddings();await SettingsRepository.set('ai_provider','on_device');await SettingsRepository.set('local_only','true');setProvider('on_device');await refreshModels();setStatus('Local AI model is active and ready.');}catch(error){setStatus(userMessage(error));await loadModels();}finally{setModelBusyId(null);}};
  const removeModel=(modelId:string,displayName:string)=>Alert.alert('Remove downloaded model?',`${displayName} can be downloaded again later.`,[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>void(async()=>{setModelBusyId(modelId);try{await ModelService.deleteModel(modelId);await refreshModels();setStatus('Downloaded model removed.');}catch(error){setStatus(userMessage(error));}finally{setModelBusyId(null);}})()}]);
  const save=async()=>{setBusy(true);try{const previousProvider=await getAIProvider();const previousConfig=await getOllamaConfig();if(provider==='ollama')await saveOllamaConfig({endpoint,generationModel,embeddingModel});else await SettingsRepository.set('ai_provider','on_device');await SettingsRepository.set('chunk_size',chunk);await SettingsRepository.set('summary_length',summaryLength);await SettingsRepository.set('local_only',provider==='on_device'?'true':'false');const nextConfig=await getOllamaConfig();if(previousProvider!==provider||JSON.stringify(previousConfig)!==JSON.stringify(nextConfig))await DocumentRepository.clearEmbeddings();setStatus('Settings saved.');}catch(error){setStatus(userMessage(error));}finally{setBusy(false);}};
  const testOllama=async()=>{setBusy(true);const previousProvider=await getAIProvider();const previousConfig=await getOllamaConfig();try{await saveOllamaConfig({endpoint,generationModel,embeddingModel});const names=await OllamaService.testConnection();const nextConfig=await getOllamaConfig();if(previousProvider!=='ollama'||JSON.stringify(previousConfig)!==JSON.stringify(nextConfig))await DocumentRepository.clearEmbeddings();setProvider('ollama');setStatus(`Connected to Ollama · ${names.length} models available.`);}catch(error){await SettingsRepository.set('ai_provider',previousProvider);setStatus(userMessage(error));}finally{setBusy(false);}};
  const clearAll=()=>Alert.alert('Clear all application data?','This permanently removes every document, note, highlight, summary and chat. Downloaded models are kept.',[{text:'Cancel',style:'cancel'},{text:'Clear',style:'destructive',onPress:()=>void(async()=>{for(const doc of await DocumentRepository.list())await removePrivateFile(doc.localFilePath);for(const doc of await DocumentRepository.list())await DocumentRepository.delete(doc.id);await loadDocuments();setStatus('All document data cleared.');})()}]);
  const navigateMain=(destination:MainDestination)=>{if(destination==='Settings')return;navigation.navigate(destination);};
  return <Screen scroll={false} includeTopInset><AppHeader title="Settings" eyebrow="System configuration"/><ScrollView style={settingsStyles.scroll} contentContainerStyle={settingsStyles.content} keyboardShouldPersistTaps="handled"><Card label="Generation model">{LLM_MODEL_OPTIONS.map(catalog=>{const record=models.find(model=>model.id===catalog.id);const installed=record?.status==='downloaded';const active=activeIds.llm===catalog.id;return <React.Fragment key={catalog.id}><Text style={styles.body}>{catalog.tier.toUpperCase()} · {catalog.displayName}{active?' · ACTIVE':''}</Text><Text style={styles.muted}>{catalog.description} {catalog.languages} · {(catalog.sizeBytes/1024**2).toFixed(0)} MB · {catalog.minimumMemoryGB} GB RAM · {record?.status??'not_downloaded'}</Text><Button title={modelBusyId===catalog.id?'Working…':active&&installed?'Active':installed?'Activate':'Download and use'} onPress={()=>void useLocalModel(catalog.id)} disabled={busy||modelBusyId!==null||(active&&installed)}/>{installed?<Button title={`Remove ${catalog.tier} model`} danger onPress={()=>removeModel(catalog.id,catalog.displayName)} disabled={busy||modelBusyId!==null}/>:null}</React.Fragment>;})}
    <Button title="Cancel download" danger onPress={()=>ModelService.cancelDownload()} disabled={modelBusyId===null}/>{status?<Text style={styles.muted}>{status} {progress>0&&progress<1?`${Math.round(progress*100)}%`:''}</Text>:null}</Card>
    <Card label="Document retrieval model">{(()=>{const catalog=getModelById(DEFAULT_EMBEDDING_MODEL_ID)!;const record=models.find(model=>model.id===catalog.id);const installed=record?.status==='downloaded';return <><Text style={styles.body}>{catalog.displayName}{activeIds.embedding===catalog.id?' · ACTIVE':''}</Text><Text style={styles.muted}>{catalog.description} {(catalog.sizeBytes/1024**2).toFixed(0)} MB · {record?.status??'not_downloaded'}</Text>{installed?<Button title="Remove retrieval model" danger onPress={()=>removeModel(catalog.id,catalog.displayName)} disabled={busy||modelBusyId!==null}/>:<Button title="Download retrieval model" onPress={()=>void(async()=>{setModelBusyId(catalog.id);try{await ModelService.downloadModel(catalog.id,(value,label)=>{setProgress(value);setStatus(`${label} · ${Math.round(value*100)}%`);});await ModelService.activate(catalog.id);await refreshModels();setStatus('Retrieval model is ready.');}catch(error){setStatus(userMessage(error));}finally{setModelBusyId(null);}})()} disabled={busy||modelBusyId!==null}/>}</>;})()}</Card>
    <Card label="AI provider"><Text style={styles.body}>Selected: {provider==='ollama'?'Ollama on local network':'On-device llama.rn'}</Text><Button title="Use Ollama" onPress={()=>setProvider('ollama')}/><Button title="Use on-device AI" onPress={()=>setProvider('on_device')}/>{provider==='ollama'?<><Field value={endpoint} onChangeText={setEndpoint} autoCapitalize="none" autoCorrect={false} placeholder="Ollama URL"/><Field value={generationModel} onChangeText={setGenerationModel} autoCapitalize="none" placeholder="Generation model"/><Field value={embeddingModel} onChangeText={setEmbeddingModel} autoCapitalize="none" placeholder="Embedding model"/><Button title={busy?'Testing…':'Test Ollama connection'} onPress={()=>void testOllama()} disabled={busy}/></>:null}</Card>
    <Card label="Generation"><Text style={styles.body}>Default chunk size (300–1200 tokens)</Text><Field value={chunk} keyboardType="number-pad" onChangeText={setChunk}/><Text style={styles.body}>Preferred summary length</Text><Field value={summaryLength} onChangeText={setSummaryLength}/><Button title="Save settings" onPress={()=>void save()} disabled={busy}/></Card>
    <Card label="Privacy"><Text style={styles.body}>{provider==='ollama'?'Ollama mode sends required excerpts to the configured computer over your local network. No cloud fallback is used.':'On-device mode keeps inference and document content on this device.'}</Text><Button title="Clear generated AI content" danger onPress={()=>void ContentRepository.clearAll().then(()=>setStatus('Generated content cleared.'))}/><Button title="Clear all application data" danger onPress={clearAll}/></Card>
    <Card label="About"><Text style={styles.body}>LocalNote AI {version}</Text><Text style={styles.muted}>On-device OCR, optional local-network inference and private SQLite storage.</Text></Card></ScrollView><BottomNavigation active="Settings" onNavigate={navigateMain}/></Screen>};

const settingsStyles=StyleSheet.create({scroll:{flex:1},content:{gap:16,paddingVertical:10}});
