import React,{useEffect,useMemo,useState} from 'react';
import {Alert,FlatList,Pressable,Text,View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/types';
import type {Citation,DocumentRecord,GenerationType,NoteRecord,SectionRecord} from '../types/domain';
import {Button,Card,Field,Loading,Screen,Title,colors,styles} from '../components/ui';
import {ChatRepository,ContentRepository,DocumentRepository,HighlightRepository,NoteRepository} from '../database/repositories';
import {LocalNotePipeline} from '../services/LocalNotePipeline';
import {ModelService} from '../ai/ModelService';
import {userMessage} from '../types/errors';
import {removePrivateFile} from '../documents/importer';
import {useAppStore} from '../stores/useAppStore';

type Props=NativeStackScreenProps<RootStackParamList,'Workspace'>;type Tab='Overview'|'Reader'|'Notes'|'Ask'|'Details';
const outputs:Array<{type:GenerationType;label:string}>=[{type:'short_summary',label:'Short summary'},{type:'detailed_summary',label:'Detailed summary'},{type:'key_points',label:'Key points'},{type:'important_terms',label:'Important terms'},{type:'simplified_explanation',label:'Simplified explanation'},{type:'revision_questions',label:'Revision questions'}];

export const WorkspaceScreen=({route,navigation}:Props)=>{const {documentId}=route.params;const [tab,setTab]=useState<Tab>('Overview');const [document,setDocument]=useState<DocumentRecord|null>(null);const [sections,setSections]=useState<SectionRecord[]>([]);const [contents,setContents]=useState<Record<string,string>>({});const [notes,setNotes]=useState<NoteRecord[]>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [readerSearch,setReaderSearch]=useState(route.params.initialSearch??'');const [fontSize,setFontSize]=useState(16);const reloadLibrary=useAppStore(s=>s.loadDocuments);
  const reload=React.useCallback(async()=>{const [doc,sectionRows,contentRows,noteRows]=await Promise.all([DocumentRepository.get(documentId),DocumentRepository.sections(documentId),ContentRepository.getAll(documentId),NoteRepository.list(documentId)]);setDocument(doc);setSections(sectionRows);setContents(contentRows);setNotes(noteRows);},[documentId]);
  useEffect(()=>{void DocumentRepository.markOpened(documentId);void reload();},[documentId,reload]);
  if(!document)return <Screen><Loading label="Opening document…"/></Screen>;
  const generate=async(type:GenerationType)=>{setBusy(type);setError('');try{await LocalNotePipeline.generateSummary(documentId,type);await reload();}catch(e){setError(userMessage(e));}finally{setBusy('');}};
  const openCitation=(citation:Citation)=>{setReaderSearch(citation.excerpt.slice(0,50));setTab('Reader');};
  const remove=()=>Alert.alert('Delete this document?','This permanently removes the private source file and all related local data.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void(async()=>{const doc=await DocumentRepository.delete(documentId);if(doc)await removePrivateFile(doc.localFilePath);await reloadLibrary();navigation.popTo('Library');})()}]);
  return <Screen scroll={false}><Title>{document.title}</Title><View style={{flexDirection:'row',flexWrap:'wrap',gap:6}}>{(['Overview','Reader','Notes','Ask','Details'] as Tab[]).map(value=><Pressable key={value} onPress={()=>setTab(value)} style={{paddingHorizontal:11,paddingVertical:9,borderRadius:20,backgroundColor:tab===value?colors.primary:colors.surface}}><Text style={{color:tab===value?'white':colors.ink,fontWeight:'700'}}>{value}</Text></Pressable>)}</View>
    {error?<Card label="Action needed"><Text style={styles.body}>{error}</Text></Card>:null}
    <View style={{flex:1}}>{tab==='Overview'?<Overview contents={contents} busy={busy} generate={generate}/>:tab==='Reader'?<Reader sections={sections} search={readerSearch} setSearch={setReaderSearch} fontSize={fontSize} setFontSize={setFontSize}/>:tab==='Notes'?<Notes document={document} sections={sections} notes={notes} reload={reload}/>:tab==='Ask'?<Ask documentId={documentId} busy={busy} setBusy={setBusy} setError={setError} openCitation={openCitation}/>:<Details document={document} sectionCount={sections.length} onDelete={remove}/>}</View>
  </Screen>};

const Overview=({contents,busy,generate}:{contents:Record<string,string>;busy:string;generate:(type:GenerationType)=>Promise<void>})=><FlatList data={outputs} keyExtractor={item=>item.type} contentContainerStyle={{gap:12,paddingVertical:12}} renderItem={({item})=><Card label="AI-generated"><Text style={[styles.body,{fontWeight:'800'}]}>{item.label}</Text>{contents[item.type]?<Text selectable style={styles.body}>{contents[item.type]}</Text>:<Text style={styles.muted}>Not generated yet.</Text>}<Button title={busy===item.type?'Generating…':contents[item.type]?'Regenerate':'Generate'} disabled={Boolean(busy)} onPress={()=>void generate(item.type)}/></Card>}/>;

const Reader=({sections,search,setSearch,fontSize,setFontSize}:{sections:SectionRecord[];search:string;setSearch:(v:string)=>void;fontSize:number;setFontSize:(v:number)=>void})=>{const visible=useMemo(()=>search.trim()?sections.filter(s=>s.text.toLowerCase().includes(search.toLowerCase())):sections,[sections,search]);return <View style={{flex:1,gap:10}}><Field value={search} onChangeText={setSearch} placeholder="Search inside document"/><View style={{flexDirection:'row',gap:8}}><Button title="A−" onPress={()=>setFontSize(Math.max(12,fontSize-2))}/><Button title="A+" onPress={()=>setFontSize(Math.min(28,fontSize+2))}/></View><FlatList data={visible} keyExtractor={item=>item.id} contentContainerStyle={{gap:12,paddingBottom:18}} ListEmptyComponent={<Card><Text style={styles.body}>No matches.</Text></Card>} renderItem={({item})=><Card label={`Source text · page ${item.pageStart}`}><Text style={[styles.body,{fontSize,lineHeight:fontSize*1.55,fontWeight:'800'}]}>{item.title}</Text><Text selectable style={[styles.body,{fontSize,lineHeight:fontSize*1.55}]}>{item.text}</Text></Card>}/></View>};

const Notes=({document,sections,notes,reload}:{document:DocumentRecord;sections:SectionRecord[];notes:NoteRecord[];reload:()=>Promise<void>})=>{const [editing,setEditing]=useState<NoteRecord|null>(null);const [title,setTitle]=useState('');const [content,setContent]=useState('');const [excerpt,setExcerpt]=useState('');const save=async()=>{const id=await NoteRepository.save({id:editing?.id,documentId:document.id,sectionId:null,title:title.trim()||'My note',content,isPinned:editing?.isPinned??false});if(excerpt.trim()){const start=document.extractedText.indexOf(excerpt.trim());await HighlightRepository.save({documentId:document.id,sectionId:sections.find(s=>start>=s.characterStart&&start<=s.characterEnd)?.id??null,noteId:id,selectedText:excerpt.trim(),characterStart:Math.max(0,start),characterEnd:Math.max(0,start)+excerpt.trim().length});}setEditing(null);setTitle('');setContent('');setExcerpt('');await reload();};
  const edit=(note:NoteRecord)=>{setEditing(note);setTitle(note.title);setContent(note.content);};return <FlatList data={notes} keyExtractor={item=>item.id} contentContainerStyle={{gap:12,paddingVertical:12}} ListHeaderComponent={<Card label="My note"><Field value={title} onChangeText={setTitle} placeholder="Title"/><Field multiline value={content} onChangeText={setContent} placeholder="Write a note"/><Field multiline value={excerpt} onChangeText={setExcerpt} placeholder="Optional: paste selected source excerpt to highlight"/><Button title={editing?'Update note':'Create note'} disabled={!content.trim()} onPress={()=>void save()}/></Card>}
  ListEmptyComponent={<Card><Text style={styles.muted}>No notes yet.</Text></Card>} renderItem={({item})=><Card label={item.isPinned?'My note · pinned':'My note'}><Text style={[styles.body,{fontWeight:'800'}]}>{item.title}</Text><Text style={styles.body}>{item.content}</Text><View style={{gap:8}}><Button title="Edit" onPress={()=>edit(item)}/><Button title={item.isPinned?'Unpin':'Pin'} onPress={()=>void NoteRepository.save({...item,isPinned:!item.isPinned}).then(reload)}/><Button title="Delete" danger onPress={()=>void NoteRepository.remove(item.id).then(reload)}/></View></Card>}/>};

const Ask=({documentId,busy,setBusy,setError,openCitation}:{documentId:string;busy:string;setBusy:(v:string)=>void;setError:(v:string)=>void;openCitation:(c:Citation)=>void})=>{const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [stream,setStream]=useState('');const [citations,setCitations]=useState<Citation[]>([]);const ask=async()=>{setBusy('ask');setError('');setAnswer('');setStream('');try{let current='';const result=await LocalNotePipeline.ask(documentId,question,token=>{current+=token;setStream(current);});setAnswer(result.answer);setCitations(result.citations);await ChatRepository.saveExchange(documentId,question,result.answer,result.citations.map(c=>c.chunkId));}catch(e){setError(userMessage(e));}finally{setBusy('');setStream('');}};
  return <Screen><Card label="Ask this document"><Field value={question} onChangeText={setQuestion} placeholder="Ask a source-grounded question" multiline/><Button title={busy==='ask'?'Generating…':'Ask'} onPress={()=>void ask()} disabled={Boolean(busy)||!question.trim()}/>{busy==='ask'?<Button title="Cancel generation" danger onPress={()=>void ModelService.cancelGeneration()}/>:null}</Card>{stream?<Card label="AI-generated · streaming"><Text style={styles.body}>{stream}</Text></Card>:null}{answer?<Card label="AI-generated"><Text style={styles.body}>{answer}</Text>{citations.map(c=><Pressable key={c.chunkId} onPress={()=>openCitation(c)}><Text style={{color:colors.primary,fontWeight:'700'}}>Source: {c.sectionTitle} · page {c.pageStart}</Text><Text style={styles.muted}>{c.excerpt.slice(0,180)}…</Text></Pressable>)}</Card>:null}</Screen>};

const Details=({document,sectionCount,onDelete}:{document:DocumentRecord;sectionCount:number;onDelete:()=>void})=><Screen><Card label="Document details"><Text style={styles.body}>Original file: {document.originalFilename}</Text><Text style={styles.body}>Private path: {document.localFilePath.replace(/^.*\/Documents\//,'Documents/')}</Text><Text style={styles.body}>Type: {document.fileType.toUpperCase()}</Text><Text style={styles.body}>Size: {(document.fileSize/1024).toFixed(1)} KB</Text><Text style={styles.body}>Pages: {document.pageCount}</Text><Text style={styles.body}>Words: {document.wordCount}</Text><Text style={styles.body}>Characters: {document.characterCount}</Text><Text style={styles.body}>Sections: {sectionCount}</Text><Text style={styles.body}>Embeddings: {document.embeddingStatus}</Text><Text style={styles.body}>Imported: {new Date(document.createdAt).toLocaleString()}</Text></Card><Button title="Delete document and related data" danger onPress={onDelete}/></Screen>;
