import React,{useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import {Alert,FlatList,Platform,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/types';
import type {Citation,DocumentListRecord,GenerationType,NoteRecord,SectionRecord} from '../types/domain';
import {Button,Card,Field,Loading,Screen,colors,fontFamilies,styles} from '../components/ui';
import {AppHeader,BottomNavigation,type MainDestination} from '../components/AppChrome';
import {ContentRepository,DocumentRepository,HighlightRepository,NoteRepository} from '../database/repositories';
import {BackgroundGenerationService} from '../services/BackgroundGenerationService';
import {userMessage} from '../types/errors';
import {removePrivateFile} from '../documents/importer';
import {useAppStore} from '../stores/useAppStore';

type Props=NativeStackScreenProps<RootStackParamList,'Workspace'>;type Tab='Overview'|'Reader'|'Notes'|'Ask'|'Details';
const outputs:Array<{type:GenerationType;label:string}>=[{type:'short_summary',label:'Short summary'},{type:'detailed_summary',label:'Detailed summary'},{type:'key_points',label:'Key points'},{type:'important_terms',label:'Important terms'},{type:'simplified_explanation',label:'Simplified explanation'},{type:'revision_questions',label:'Revision questions'}];

export const WorkspaceScreen=({route,navigation}:Props)=>{const {documentId}=route.params;const [tab,setTab]=useState<Tab>('Overview');const [document,setDocument]=useState<DocumentListRecord|null>(null);const [sections,setSections]=useState<SectionRecord[]>([]);const [contents,setContents]=useState<Record<string,string>>({});const [notes,setNotes]=useState<NoteRecord[]>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [readerSearch,setReaderSearch]=useState(route.params.initialSearch??'');const [fontSize,setFontSize]=useState(16);const reloadLibrary=useAppStore(s=>s.loadDocuments);
  const reload=React.useCallback(async()=>{const [doc,sectionRows,contentRows,noteRows]=await Promise.all([DocumentRepository.getMetadata(documentId),DocumentRepository.sections(documentId),ContentRepository.getAll(documentId),NoteRepository.list(documentId)]);setDocument(doc);setSections(sectionRows);setContents(contentRows);setNotes(noteRows);},[documentId]);
  useEffect(()=>{void DocumentRepository.markOpened(documentId);void reload();},[documentId,reload]);
  useEffect(()=>navigation.addListener('focus',()=>void reload()),[navigation,reload]);
  useEffect(()=>BackgroundGenerationService.subscribe(()=>void reload()),[reload]);
  if(!document)return <Screen includeTopInset><Loading label="Opening document…"/></Screen>;
  const generate=async(type:GenerationType)=>{setBusy(type);setError('');try{await BackgroundGenerationService.generateSummary(documentId,type);await reload();}catch(e){setError(userMessage(e));}finally{setBusy('');}};
  const openCitation=(citation:Citation)=>{setReaderSearch(citation.excerpt.slice(0,50));setTab('Reader');};
  const remove=()=>Alert.alert('Delete this document?','This permanently removes the private source file and all related local data.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void(async()=>{const doc=await DocumentRepository.delete(documentId);if(doc)await removePrivateFile(doc.localFilePath);await reloadLibrary();navigation.popTo('Library');})()}]);
  const navigateMain=(destination:MainDestination)=>{if(destination==='Library')navigation.popTo('Library');else navigation.navigate(destination);};
  return <Screen scroll={false} includeTopInset><AppHeader title="Archive" onBack={()=>navigation.popTo('Library')}/><View style={workspaceStyles.identity}><Text style={workspaceStyles.hash}>DOCUMENT HASH · {document.id.slice(0,8).toUpperCase()}</Text><Text numberOfLines={3} style={workspaceStyles.documentTitle}>{document.title}</Text></View><View style={workspaceStyles.tabs}>{(['Overview','Reader','Notes','Ask','Details'] as Tab[]).map(value=><Pressable key={value} accessibilityRole="tab" accessibilityState={{selected:tab===value}} onPress={()=>setTab(value)} style={[workspaceStyles.tab,tab===value&&workspaceStyles.activeTab]}><Text style={[workspaceStyles.tabText,tab===value&&workspaceStyles.activeTabText]}>{value.toUpperCase()}</Text></Pressable>)}</View>
    {error?<Card label="Action needed"><Text style={styles.body}>{error}</Text></Card>:null}
    <View style={{flex:1}}>{tab==='Overview'?<Overview contents={contents} busy={busy} generate={generate}/>:tab==='Reader'?<Reader sections={sections} search={readerSearch} setSearch={setReaderSearch} fontSize={fontSize} setFontSize={setFontSize}/>:tab==='Notes'?<Notes document={document} sections={sections} notes={notes} reload={reload}/>:tab==='Ask'?<Ask documentId={documentId} busy={busy} setBusy={setBusy} setError={setError} openCitation={openCitation}/>:<Details document={document} sectionCount={sections.length} onDelete={remove}/>}</View>
    <BottomNavigation active="Library" onNavigate={navigateMain}/></Screen>};

const Overview=({contents,busy,generate}:{contents:Record<string,string>;busy:string;generate:(type:GenerationType)=>Promise<void>})=><FlatList data={outputs} keyExtractor={item=>item.type} contentContainerStyle={workspaceStyles.tabContent} renderItem={({item})=><Card label="AI-generated · v1"><Text style={workspaceStyles.sectionTitle}>{item.label}</Text>{contents[item.type]?<Text selectable style={styles.body}>{contents[item.type]}</Text>:<Text style={styles.muted}>Not generated yet.</Text>}{busy===item.type?<Text style={styles.muted}>Running as a saved job. You can switch apps; Android keeps an ongoing notification and iOS resumes if its background time expires.</Text>:null}<Button title={busy===item.type?'Generating in background…':contents[item.type]?'Regenerate':'Generate'} disabled={Boolean(busy)} onPress={()=>void generate(item.type)}/></Card>}/>;

const Reader=({sections,search,setSearch,fontSize,setFontSize}:{sections:SectionRecord[];search:string;setSearch:(v:string)=>void;fontSize:number;setFontSize:(v:number)=>void})=>{const deferredSearch=useDeferredValue(search.trim().toLowerCase());const visible=useMemo(()=>deferredSearch?sections.filter(section=>section.text.toLowerCase().includes(deferredSearch)):sections,[sections,deferredSearch]);return <View style={workspaceStyles.reader}><View style={workspaceStyles.readerTools}><View style={{flex:1}}><Field value={search} onChangeText={setSearch} placeholder="Search archive…"/></View><Button title="A−" variant="secondary" onPress={()=>setFontSize(Math.max(12,fontSize-2))}/><Button title="A+" variant="secondary" onPress={()=>setFontSize(Math.min(28,fontSize+2))}/></View><FlatList data={visible} keyExtractor={item=>item.id} contentContainerStyle={workspaceStyles.tabContent} initialNumToRender={3} maxToRenderPerBatch={3} updateCellsBatchingPeriod={40} windowSize={5} removeClippedSubviews={Platform.OS==='android'} ListEmptyComponent={<Card><Text style={styles.body}>No matches.</Text></Card>} renderItem={({item})=><Card label={`Source · folio ${item.pageStart}`}><Text style={[workspaceStyles.sectionTitle,{fontSize:fontSize+5,lineHeight:(fontSize+5)*1.25}]}>{item.title}</Text><Text selectable style={[styles.body,{fontSize,lineHeight:fontSize*1.55}]}>{item.text}</Text></Card>}/></View>};

const Notes=({document,sections,notes,reload}:{document:DocumentListRecord;sections:SectionRecord[];notes:NoteRecord[];reload:()=>Promise<void>})=>{const [editing,setEditing]=useState<NoteRecord|null>(null);const [title,setTitle]=useState('');const [content,setContent]=useState('');const [excerpt,setExcerpt]=useState('');const save=async()=>{const id=await NoteRepository.save({id:editing?.id,documentId:document.id,sectionId:null,title:title.trim()||'My note',content,isPinned:editing?.isPinned??false});if(excerpt.trim()){const selectedText=excerpt.trim();const section=sections.find(item=>item.text.includes(selectedText));const localStart=section?.text.indexOf(selectedText)??0;const start=(section?.characterStart??0)+Math.max(0,localStart);await HighlightRepository.save({documentId:document.id,sectionId:section?.id??null,noteId:id,selectedText,characterStart:start,characterEnd:start+selectedText.length});}setEditing(null);setTitle('');setContent('');setExcerpt('');await reload();};
  const edit=(note:NoteRecord)=>{setEditing(note);setTitle(note.title);setContent(note.content);};return <FlatList data={notes} keyExtractor={item=>item.id} contentContainerStyle={{gap:12,paddingVertical:12}} ListHeaderComponent={<Card label="My note"><Field value={title} onChangeText={setTitle} placeholder="Title"/><Field multiline value={content} onChangeText={setContent} placeholder="Write a note"/><Field multiline value={excerpt} onChangeText={setExcerpt} placeholder="Optional: paste selected source excerpt to highlight"/><Button title={editing?'Update note':'Create note'} disabled={!content.trim()} onPress={()=>void save()}/></Card>}
  ListEmptyComponent={<Card><Text style={styles.muted}>No notes yet.</Text></Card>} renderItem={({item})=><Card label={item.isPinned?'My note · pinned':'My note'}><Text style={[styles.body,{fontWeight:'800'}]}>{item.title}</Text><Text style={styles.body}>{item.content}</Text><View style={{gap:8}}><Button title="Edit" onPress={()=>edit(item)}/><Button title={item.isPinned?'Unpin':'Pin'} onPress={()=>void NoteRepository.save({...item,isPinned:!item.isPinned}).then(reload)}/><Button title="Delete" danger onPress={()=>void NoteRepository.remove(item.id).then(reload)}/></View></Card>}/>};

const Ask=({documentId,busy,setBusy,setError,openCitation}:{documentId:string;busy:string;setBusy:(v:string)=>void;setError:(v:string)=>void;openCitation:(c:Citation)=>void})=>{const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [stream,setStream]=useState('');const [citations,setCitations]=useState<Citation[]>([]);const streamBuffer=useRef('');const streamTimer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>{const restore=()=>void BackgroundGenerationService.latestAsk(documentId).then(result=>{if(result){setAnswer(result.answer);setCitations(result.citations);}});restore();return BackgroundGenerationService.subscribe(restore);},[documentId]);useEffect(()=>()=>{if(streamTimer.current)clearTimeout(streamTimer.current);},[]);const ask=async()=>{setBusy('ask');setError('');setAnswer('');setStream('');streamBuffer.current='';if(streamTimer.current)clearTimeout(streamTimer.current);streamTimer.current=null;try{const result=await BackgroundGenerationService.ask(documentId,question,token=>{streamBuffer.current+=token;if(streamTimer.current===null)streamTimer.current=setTimeout(()=>{setStream(streamBuffer.current);streamTimer.current=null;},64);});setAnswer(result.answer);setCitations(result.citations);}catch(e){setError(userMessage(e));}finally{if(streamTimer.current)clearTimeout(streamTimer.current);streamTimer.current=null;streamBuffer.current='';setBusy('');setStream('');}};
  return <ScrollView contentContainerStyle={workspaceStyles.tabContent} keyboardShouldPersistTaps="handled"><Card label="Inquiry engine"><Field value={question} onChangeText={setQuestion} placeholder="Enter a scholarly inquiry regarding this source…" multiline/>{busy==='ask'?<Text style={styles.muted}>This saved Ask job can continue while you switch apps. Its answer will be restored when you return.</Text>:null}<Button title={busy==='ask'?'Generating in background…':'Ask'} onPress={()=>void ask()} disabled={Boolean(busy)||!question.trim()}/>{busy==='ask'?<Button title="Cancel generation" danger onPress={()=>void BackgroundGenerationService.cancelActive()}/>:null}</Card><Card label="Suggested inquiries"><Button title="Summarize the primary requirements" variant="secondary" onPress={()=>setQuestion('Summarize the primary requirements and cite the supporting sections.')}/><Button title="Identify recurring themes" variant="secondary" onPress={()=>setQuestion('Identify recurring themes in this document and cite the evidence.')}/></Card>{stream?<Card label="AI-generated · streaming"><Text style={styles.body}>{stream}</Text></Card>:null}{answer?<Card label="AI-generated · grounded"><Text style={styles.body}>{answer}</Text>{citations.map(c=><Pressable key={c.chunkId} onPress={()=>openCitation(c)}><Text style={workspaceStyles.citation}>SOURCE: {c.sectionTitle.toUpperCase()} · PAGE {c.pageStart}</Text><Text style={styles.muted}>{c.excerpt.slice(0,180)}…</Text></Pressable>)}</Card>:null}</ScrollView>};

const Details=({document,sectionCount,onDelete}:{document:DocumentListRecord;sectionCount:number;onDelete:()=>void})=><ScrollView contentContainerStyle={workspaceStyles.tabContent}><Card label="Document metrics"><Text style={styles.body}>Original file: {document.originalFilename}</Text><Text style={styles.body}>Private path: {document.localFilePath.replace(/^.*\/Documents\//,'Documents/')}</Text><Text style={styles.body}>Type: {document.fileType.toUpperCase()}</Text><Text style={styles.body}>Size: {(document.fileSize/1024).toFixed(1)} KB</Text><Text style={styles.body}>Pages: {document.pageCount}</Text><Text style={styles.body}>Words: {document.wordCount}</Text><Text style={styles.body}>Characters: {document.characterCount}</Text><Text style={styles.body}>Sections: {sectionCount}</Text><Text style={styles.body}>Embeddings: {document.embeddingStatus}</Text><Text style={styles.body}>Imported: {new Date(document.createdAt).toLocaleString()}</Text></Card><Button title="Delete document and related data" danger onPress={onDelete}/></ScrollView>;

const workspaceStyles=StyleSheet.create({identity:{gap:7,paddingVertical:4},hash:{fontFamily:fontFamilies.mono,fontSize:9,fontWeight:'700',letterSpacing:1.4,color:colors.muted},documentTitle:{fontFamily:fontFamilies.serif,fontSize:28,lineHeight:34,fontStyle:'italic',fontWeight:'700',color:colors.ink},tabs:{flexDirection:'row',flexWrap:'wrap',borderBottomWidth:1,borderColor:colors.line,gap:8},tab:{paddingHorizontal:3,paddingVertical:9,borderBottomWidth:2,borderBottomColor:'transparent'},activeTab:{borderBottomColor:colors.ink},tabText:{fontFamily:fontFamilies.mono,fontSize:8,fontWeight:'700',letterSpacing:1.1,color:colors.muted},activeTabText:{color:colors.ink},tabContent:{gap:14,paddingVertical:12},sectionTitle:{fontFamily:fontFamilies.serif,fontSize:24,lineHeight:30,fontWeight:'700',color:colors.ink},reader:{flex:1,gap:10},readerTools:{flexDirection:'row',alignItems:'center',gap:8},citation:{fontFamily:fontFamilies.mono,fontSize:10,fontWeight:'700',letterSpacing:.7,color:colors.accent,marginTop:12}});
