import React, {type PropsWithChildren} from 'react';
import {ActivityIndicator,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View,type TextInputProps} from 'react-native';
import {SafeAreaView,type Edge} from 'react-native-safe-area-context';

export const colors={bg:'#00172F',surface:'#062442',surfaceDeep:'#001126',ink:'#FFFBD1',body:'#D5E1EB',muted:'#8FA9BF',primary:'#FFFBD1',primaryInk:'#00172F',accent:'#9CCBFF',danger:'#B90017',line:'#294765',ai:'#082C50',note:'#263B4E'};
export const fontFamilies={serif:Platform.select({ios:'Georgia',android:'serif',default:'serif'}),mono:Platform.select({ios:'Menlo',android:'monospace',default:'monospace'})};
export const Screen=({children,scroll=true,includeTopInset=false,safeArea=true}:{children:React.ReactNode;scroll?:boolean;includeTopInset?:boolean;safeArea?:boolean})=>{const edges:Edge[]=safeArea?(includeTopInset?['top','bottom','left','right']:['bottom','left','right']):[];return <SafeAreaView edges={edges} style={styles.safeArea}>{scroll?<ScrollView contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled">{children}</ScrollView>:<View style={styles.screen}>{children}</View>}</SafeAreaView>;};
export const Card=({children,label}:{children:React.ReactNode;label?:string})=><View style={styles.card}>{label?<Text style={styles.label}>{label}</Text>:null}{children}</View>;
export const Button=({title,onPress,disabled=false,danger=false,variant='primary'}:{title:string;onPress:()=>void;disabled?:boolean;danger?:boolean;variant?:'primary'|'secondary'|'ghost'})=><Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={[styles.button,variant==='secondary'&&styles.secondaryButton,variant==='ghost'&&styles.ghostButton,danger&&styles.danger,disabled&&styles.disabled]}><Text style={[styles.buttonText,(variant==='secondary'||variant==='ghost'||danger)&&styles.secondaryButtonText]}>{title.toUpperCase()}</Text></Pressable>;
export const Field=(props:TextInputProps)=><TextInput placeholderTextColor={colors.muted} {...props} style={[styles.input,props.multiline&&styles.multiline,props.style]}/>;
export const Loading=({label='Loading…'}:{label?:string})=><View style={styles.loading}><ActivityIndicator color={colors.accent}/><Text style={styles.muted}>{label}</Text></View>;
export const Title=({children}:PropsWithChildren)=><Text style={styles.title}>{children}</Text>;
export const styles=StyleSheet.create({safeArea:{flex:1,backgroundColor:colors.bg},screen:{flexGrow:1,paddingHorizontal:18,paddingTop:14,gap:14,backgroundColor:colors.bg},card:{backgroundColor:colors.surfaceDeep,padding:18,gap:12,borderWidth:1,borderColor:colors.line},
  title:{fontFamily:fontFamilies.serif,fontSize:32,lineHeight:38,fontWeight:'700',color:colors.ink},label:{fontFamily:fontFamilies.mono,fontSize:10,fontWeight:'700',textTransform:'uppercase',letterSpacing:1.6,color:colors.accent},body:{fontFamily:fontFamilies.serif,fontSize:17,lineHeight:26,color:colors.body},muted:{fontFamily:fontFamilies.mono,fontSize:11,lineHeight:17,color:colors.muted},
  button:{minHeight:44,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',paddingHorizontal:16,borderWidth:1,borderColor:colors.primary},secondaryButton:{backgroundColor:'transparent',borderColor:colors.line},ghostButton:{minHeight:38,backgroundColor:'transparent',borderColor:'transparent'},danger:{backgroundColor:colors.danger,borderColor:colors.danger},disabled:{opacity:.4},buttonText:{fontFamily:fontFamilies.mono,color:colors.primaryInk,fontSize:11,fontWeight:'700',letterSpacing:1.5},secondaryButtonText:{color:colors.ink},
  input:{minHeight:52,borderWidth:1,borderColor:colors.line,paddingHorizontal:14,color:colors.ink,backgroundColor:colors.surfaceDeep,fontFamily:fontFamilies.mono,fontSize:13},multiline:{minHeight:130,textAlignVertical:'top',paddingTop:12},loading:{flexDirection:'row',gap:10,alignItems:'center'}});
